sudo: required

dist: trusty

services:
  - docker

script:
  - sudo make

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [ "$BRANCH" == "master" ]; then
      sudo make publish;
    else
      sudo make publish-beta;
    fi
